export const defaultWeather: Weather = {
	location: {
		name: '',
		region: '',
		country: '',
		lat: 0,
		lon: 0,
		tz_id: '',
		localtime_epoch: 0,
		localtime: '',
	},
	current: {
		last_updated_epoch: 0,
		last_updated: '',
		temp_c: 0,
		temp_f: 0,
		is_day: 0,
		condition: {
			text: '',
			icon: '',
			code: 0,
		},
		wind_mph: 0,
		wind_kph: 0,
		wind_degree: 0,
		wind_dir: '',
		pressure_mb: 0,
		pressure_in: 0,
		precip_mm: 0,
		precip_in: 0,
		humidity: 0,
		cloud: 0,
		feelslike_c: 0,
		feelslike_f: 0,
		vis_km: 0,
		vis_miles: 0,
		uv: 0,
		gust_mph: 0,
		gust_kph: 0,
		air_quality: {
			co: 0,
			no2: 0,
			o3: 0,
			so2: 0,
			pm2_5: 0,
			pm10: 0,
			'us-epa-index': 0,
			'gb-defra-index': 0,
		},
	},
};

// export const defaultWeather: Weather = {
// 	location: {
// 		name: 'Hyderabad',
// 		region: 'Andhra Pradesh',
// 		country: 'India',
// 		lat: 17.38,
// 		lon: 78.47,
// 		tz_id: 'Asia/Kolkata',
// 		localtime_epoch: 1702894389,
// 		localtime: '2023-12-18 15:43',
// 	},
// 	current: {
// 		last_updated_epoch: 1702893600,
// 		last_updated: '2023-12-18 15:30',
// 		temp_c: 26.0,
// 		temp_f: 78.8,
// 		is_day: 1,
// 		condition: {
// 			text: 'Mist',
// 			icon: '//cdn.weatherapi.com/weather/64x64/day/143.png',
// 			code: 1030,
// 		},
// 		wind_mph: 4.3,
// 		wind_kph: 6.8,
// 		wind_degree: 50,
// 		wind_dir: 'NE',
// 		pressure_mb: 1017.0,
// 		pressure_in: 30.03,
// 		precip_mm: 0.0,
// 		precip_in: 0.0,
// 		humidity: 39,
// 		cloud: 50,
// 		feelslike_c: 25.7,
// 		feelslike_f: 78.3,
// 		vis_km: 5.0,
// 		vis_miles: 3.0,
// 		uv: 7.0,
// 		gust_mph: 9.3,
// 		gust_kph: 14.9,
// 		air_quality: {
// 			co: 627.5,
// 			no2: 14.7,
// 			o3: 90.1,
// 			so2: 18.6,
// 			pm2_5: 96.3,
// 			pm10: 104.6,
// 			'us-epa-index': 4,
// 			'gb-defra-index': 10,
// 		},
// 	},
// };
